// Generated by CoffeeScript 1.6.0
(function() {
  var DOMReady, createVisualization, intervals, map, markerLayer;

  map = null;

  markerLayer = null;

  intervals = ['2005', '2006', '2007', '2008', '2009', '2010q1', '2010q2', '2010q3', '2010q4', '2011q1', '2011q2', '2011q3', '2011q4', '2012q1', '2012q2', '2012q3', '2012q4', '2013q1', '2013q2', '2013q3', '2013q4'];

  createVisualization = function(d1, d2) {
    var datum, deed, deeds, key, lat, lon, pin, pins, s, value, _i, _j, _len, _len1;
    markerLayer = new L.LayerGroup();
    pins = d1['2011q4'];
    for (_i = 0, _len = pins.length; _i < _len; _i++) {
      pin = pins[_i];
      datum = d2[pin];
      lat = datum.lat;
      lon = datum.lon;
      deeds = datum.deeds;
      s = "";
      for (_j = 0, _len1 = deeds.length; _j < _len1; _j++) {
        deed = deeds[_j];
        for (key in deed) {
          value = deed[key];
          s += "" + pin + ", " + key + ", " + value;
        }
        s += "<br>";
      }
      L.marker([lat, lon]).addTo(markerLayer).bindPopup(s);
    }
    markerLayer.addTo(map);
    return $("input[type='range']").on('change', function(e) {
      var interval, _k, _l, _len2, _len3, _results;
      interval = intervals[e.target.value];
      markerLayer.clearLayers();
      console.log(interval);
      pins = d1[interval];
      _results = [];
      for (_k = 0, _len2 = pins.length; _k < _len2; _k++) {
        pin = pins[_k];
        datum = d2[pin];
        lat = datum.lat;
        lon = datum.lon;
        deeds = datum.deeds;
        s = "";
        for (_l = 0, _len3 = deeds.length; _l < _len3; _l++) {
          deed = deeds[_l];
          for (key in deed) {
            value = deed[key];
            s += "" + pin + ", " + key + ", " + value;
          }
          s += "<br>";
        }
        _results.push(L.marker([lat, lon]).addTo(markerLayer).bindPopup(s));
      }
      return _results;
    });
  };

  DOMReady = function() {
    var dfd1, dfd2;
    map = L.map('map').setView([41.7922, -87.6378], 15);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    dfd1 = new $.Deferred();
    dfd2 = new $.Deferred();
    $.when(dfd1, dfd2).done(createVisualization);
    $.getJSON('../data/intervals.json').done(function(data) {
      return dfd1.resolve(data);
    });
    $.getJSON('../data/deeds.json').done(function(data) {
      return dfd2.resolve(data);
    });
    return $.getJSON('../data/englewood.geojson').done(function(data) {
      return L.geoJson(data).addTo(map);
    });
  };

  window.addEventListener('DOMContentLoaded', DOMReady, false);

}).call(this);
