// Generated by CoffeeScript 1.6.0
(function() {
  var DOMReady;

  DOMReady = function() {
    var map;
    map = L.map('map').setView([41.7922, -87.6378], 16);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    return $.getJSON('../scripts/deeds.json').done(function(data) {
      var datum, deed, deeds, key, lat, lon, pin, pins, s, value, _i, _j, _len, _len1, _results;
      pins = Object.keys(data);
      _results = [];
      for (_i = 0, _len = pins.length; _i < _len; _i++) {
        pin = pins[_i];
        datum = data[pin];
        lat = datum.lat;
        lon = datum.lon;
        deeds = datum.deeds;
        s = "";
        for (_j = 0, _len1 = deeds.length; _j < _len1; _j++) {
          deed = deeds[_j];
          for (key in deed) {
            value = deed[key];
            s += "" + key + ", " + value;
          }
          s += "<br>";
        }
        _results.push(L.marker([lat, lon]).addTo(map).bindPopup(s));
      }
      return _results;
    });
  };

  window.addEventListener('DOMContentLoaded', DOMReady, false);

}).call(this);
