// Generated by CoffeeScript 1.6.0
(function() {
  var DOMReady, createVisualization, map;

  map = null;

  createVisualization = function(d1, d2) {
    var datum, deed, deeds, key, lat, lon, pin, pins, s, value, _i, _j, _len, _len1, _results;
    console.log('createVisualization', d1, d2);
    pins = d1['2011q4'];
    _results = [];
    for (_i = 0, _len = pins.length; _i < _len; _i++) {
      pin = pins[_i];
      datum = d2[pin];
      lat = datum.lat;
      lon = datum.lon;
      deeds = datum.deeds;
      s = "";
      for (_j = 0, _len1 = deeds.length; _j < _len1; _j++) {
        deed = deeds[_j];
        for (key in deed) {
          value = deed[key];
          s += "" + pin + ", " + key + ", " + value;
        }
        s += "<br>";
      }
      _results.push(L.marker([lat, lon]).addTo(map).bindPopup(s));
    }
    return _results;
  };

  DOMReady = function() {
    var dfd1, dfd2;
    map = L.map('map').setView([41.7922, -87.6378], 15);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    dfd1 = new $.Deferred();
    dfd2 = new $.Deferred();
    $.when(dfd1, dfd2).done(createVisualization);
    $.getJSON('../scripts/data/intervals.json').done(function(data) {
      return dfd1.resolve(data);
    });
    return $.getJSON('../scripts/data/deeds.json').done(function(data) {
      return dfd2.resolve(data);
    });
  };

  window.addEventListener('DOMContentLoaded', DOMReady, false);

}).call(this);
